$sql3="INSERT INTO books (Title, Author, Category, Description, review, price) VALUES
  ('Gilead','Marilynne Robinson','Fiction','A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It is 1956 in Gilead, Iowa, towards the end of the Reverend Ames\'s life, and he is absorbed in recording his family\'s story, a legacy for the young son he will never see grow up. Haunted by his grandfather\'s presence, John tells of the rift between his grandfather and his father',3.85,500),
  ('Alice in Wonderland','Lewis Carroll','Juvenile Fiction','A little girl falls down a rabbit hole and discovers a world of nonsensical and amusing characters.',4.01,600),
  ('The Shining','Stephen King','Boys','Danny is only five years old, but he is a shiner, aglow with psychic voltage. When his father becomes caretaker of an old hotel, his visions grow out of control. Cut off by blizzards, the hotel seems to develop an evil force, and who are the mysterious guests in the supposedly empty hotel?',4.21,450),
  ('The Coalwood Way','Homer H. Hickam','Biography & Autobiography','Continuing the story of the Rocket Boys of Coalwood, West Virginia, the author recounts his senior year in high school, while the forces of change bring Coalwood to a difficult crossroads and strain threatens to tear apart the Hickam home.',4.13,750),
  ('The Norton Anthology of English Literature','Stephen Greenblatt','Literary Collections','Firmly grounded by the hallmark strengths of all Norton Anthologiesâ€”thorough and helpful introductory matter, judicious annotation, complete texts wherever possibleâ€”The Norton Anthology of English Literature has been revitalized in this Eighth Edition through the collaboration between six new editors and six seasoned ones. Under the direction of Stephen Greenblatt, General Editor, the editors have reconsidered all aspects of the anthology to make it an even better teaching tool.',4.09,650),
  ('A Tear and a Smile','Kahlil Gibran','Philosophy','Contains 56 parables, stories, and poems in Gibran\'s wholly inimitable manner. Illustrated with 4 of his own paintings and drawings, it is the most important edition to the canon of this great writer.',4.03,700),
  ('Essentials of Classic Italian Cooking','Marcella Hazan','Cooking','With more than 100 illustrations by Karin Kretschman.',4.17,450),
  ('The Code Book','Simon Singh','History','Includes a history of how codes have affected the world, from the World Wars to the death of Mary, Queen of Scots, and also looks at what the future holds for the field of cryptography.',4.31,550),
  ('Walk about','Bill Bryson','Travel','Combined in one volume are Bryson\'s Down Under, an account of his memorable walk across Australia, and A Walk in the Woods, that tells of his lengthy stroll along the longest continuous footpath in the world - The Appalachian Trail, with his old friend Stephen Katz. The Trail stretches along the East Coast of the United States, from Georgia to Maine, through some of the most arresting and celebrated landscapes in America - the Smoky Mountains, Shenandoah National Park, the Berkshire Hills of Massachusetts and the Great North Woods of Main.',4.04,850)
  ";

  if (mysqli_query($link, $sql3));
  else {
    echo "Error creating table: " . mysqli_error($link);
  }